### ISSUE TITLE
`reshape` of an immobile element type aborts instead of throwing

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#10]
```
#include "plf_hive.h"
#include <mutex>

int main() {
    plf::hive<std::mutex> h;
    for (int i=0; i < 9; ++i) h.emplace();
    try { h.reshape({2, 2}); } catch (...) {}  // calls std::terminate
}
```

At the philosophical level, I question whether "throw an exception" is really the best behavior here to begin with; would it make sense to just put a `requires` constraint on the `reshape` member function so that it wouldn't exist at all for immobile types? Or, is it still useful that you can `reshape` a hive of mutexes in the degenerate case where the reshape has no runtime effect?

Right now this program `std::terminate`s because https://github.com/mattreecebentley/plf_hive/blob/7b7763f/plf_hive.h#L3584 happens to say `throw;` — I think it's just a simple typo for `throw std::whatever_exception("message");`.

**Comment by Quuxplusone** [comment]
For similar reasons, `shrink_to_fit` fails with a template error message if the element type is immobile. This is fine; but consider using `static_assert(std::is_move_constructible_v<element_type>)` somewhere near the top level of `shrink_to_fit`, to prove to the programmer that this error is intentional.
```
int main() {
    plf::hive<std::mutex> h;
    h.shrink_to_fit();  // compiler error
}
```

**Comment by mattreecebentley** [comment]
Yes, both of these are defined with preconditions in the paper of
T shall be Cpp17MoveInsertable into hive,
therefore logically they might be defined in a requires statement.

However, looking at libstdc++'s shrink_to_fit implementation (which has 
the same precondition in N4910) it also throws rather than 
static_asserts or requires.

My guess is that this is because in degenerate cases shrink_to_fit will 
not need to reallocate. @jwakely, is that the case?


In terms of reshape, it makes more sense to throw, as in many cases (eg. 
going from more restrictive block capacities to less restrictive block 
capacities) reallocation of elements will never be necessary.
I will re-write the reshape throw to be std::length_error.

**Comment by jwakely** [comment]
Libstdc++'s `shrink_to_fit` doesn't throw for non-movable types, it just gives an error somewhere deep inside the implementation.
