### ISSUE TITLE
Overalignment of small element types?

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#19]
```
#include "plf_hive.h"
#include <cassert>
#include <cstdio>

size_t used = 0;

template<class T>
struct MyAlloc {
    using value_type = T;
    explicit MyAlloc() = default;
    template<class U> MyAlloc(MyAlloc<U>) {}
    T *allocate(size_t n) const {
        used += n * sizeof(T);
        return (T*)malloc(n * sizeof(T));
    }
    void deallocate(T *p, size_t n) const {
        used -= n * sizeof(T);
        free(p);
    }
};

int main()
{
    {
        plf::hive<char, MyAlloc<char>, plf::hive_priority::memory_use> h;
        printf("Memory used after ctor: %zu\n", used);
        h.assign(10'000'000, 'x');
        printf("Memory used after assign(10'000'000): %zu MB\n", used/1'000'000);
        h.assign(100'000'000, 'x');
        printf("Memory used after assign(100'000'000): %zu MB\n", used/1'000'000);
        h.clear();
        h.trim_capacity();
        printf("Memory used after reset: %zu\n", used);
    }
    printf("Memory used after dtor: %zu\n", used);
}
```
This program prints:
```
$ ./a.out
Memory used after ctor: 0
Memory used after assign(10'000'000): 32 MB
Memory used after assign(100'000'000): 325 MB
Memory used after reset: 590
Memory used after dtor: 0
```
This seems to be because `plf::hive` likes to "align" the `char` elements to 2 bytes each for some reason. I don't think it should be doing that.

In my fork, which doesn't overalign anything, the same program prints:
```
Memory used after ctor: 0
Memory used after assign(10'000'000): 22 MB
Memory used after assign(100'000'000): 222 MB
Memory used after reset: 0
Memory used after dtor: 0
```
(The memory-use-after-reset thing is unrelated to the present issue; it's #17.)

**Comment by mattreecebentley** [comment]
It won't work if you don't overalign it (your go at it will overwrite 
elements in adjacent cells on erasure for types smaller than 32bit).
Each element must hold 2 x skipfield_type for the doubly-linked 
index-based free list to work (I have updated paper for why list is 
doubly-linked, in the design decisions section under Erased-element 
location recording mechanism).

As it stands my current beta drops skipfield_type down to uchar type 
when sizeof(value_type) <= 10 (this reflects of the results of the 
benchmarks done prior to the last meeting, regards the performance of 
hive with different value_types sizeofs versus different skipfield_types).

This means 16-bit types won't be overaligned, only 8-bit types.
I don't forsee a lot of hive use with char types so I'm unconcerned.

If someone Is overly concerned then they can overload hive for 
char/uchar value_types such that only a singly-linked free list is used, 
which means they won't be overaligned which will reduce speed slightly 
when an element is erased which is between two skipblocks, but will 
probably overall improve performance due to not wasting cache space for 
that type. It's QoL not a bug imo.
