### ISSUE TITLE
Why does hive_limits::max exist at all?

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#22]
Following on from issue #21... actually I don't really understand the goals of `reshape` and `block_capacity_limits` in general.

Is `hive_limits.max` really supposed to be a user-specified _upper limit_ on the size of a block? What if the user sets it to something unaesthetic like `37`, is the vendor allowed to increase that to a nice sane `64`, or must we respect the `37`?

Or what if the user of a `plf::hive<short>` sets the max block size to `4`? With your implementation's current group layout, this allocates a memory block of size `(4*2 + 5*1) = 13`. That's pretty much guaranteed to waste 20% more memory than if the vendor quietly rounded the max block size up to `5`, producing a memory block of size `(5*2 + 6*1) = 16`.

Setting a min block size makes sense — too-small blocks can hurt performance. Setting a _max_ block size seems counterproductive. Thoughts?

**Comment by mattreecebentley** [comment]
Because some people will want to limit the size of blocks to fit a particular cache size, and that will vary based on element size.
Also they might work out that for their particular usage pattern, a given block size leads to the minimal number of allocations/deallocations vs wasted space.
It is probably the number one thing people have repeatedly thanked me for in terms of the container design as a whole.

**Comment by mattreecebentley** [comment]
Because some people will want to limit the size of blocks to fit a 
particular cache size, and that will vary based on element size.
Also they might work out that for their particular usage pattern, a 
given block size leads to the minimal number of 
allocations/deallocations vs wasted space.
It is probably the number one thing people have repeatedly thanked me 
for in terms of the container design as a whole.
